export const productList = [
  {
    id: "001",
    name: "Priyaasi Traditional Gold Plated Kundan Earrings",
    title: "Priyaasi Traditional Gold Plated Kundan Earrings",
    price: "₹1,774",
    original_price: "₹6,999",
    discount: "74% OFF",
    description: "Elegant traditional gold-plated earrings with intricate kundan detailing. Perfect for festive occasions and weddings.",
    material: "Gold Plated Brass",
    color: "Gold",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.5,
    reviews: 128
  },
  {
    id: "002",
    name: "Priyaasi Magenta Leaf AD...",
    price: "₹1,506",
    original_price: "₹5,999",
    discount: "75% OFF",
    description: "Beautiful magenta leaf design earrings with intricate detailing.",
    material: "Gold Plated Brass",
    color: "Pink",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.3,
    reviews: 95
  },
  {
    id: "003",
    name: "Priyaasi Solitaire American...",
    price: "₹696",
    original_price: "₹2,849",
    discount: "76% OFF",
    description: "Elegant solitaire earrings with American diamond.",
    material: "Gold Plated",
    color: "Gold",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.2,
    reviews: 87
  },
  {
    id: "004",
    name: "Fancy Folk - Kundan Studded...",
    price: "₹726",
    original_price: "₹1,500",
    discount: "52% OFF",
    description: "Traditional kundan studded earrings with folk design.",
    material: "Gold Plated",
    color: "Gold",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.1,
    reviews: 76
  },
  {
    id: "005",
    name: "Classic Curves - Gold Plated Half...",
    price: "₹537",
    original_price: "₹2,099",
    discount: "74% OFF",
    description: "Classic curved design earrings with gold plating.",
    material: "Gold Plated",
    color: "Gold",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.0,
    reviews: 65
  },
  {
    id: "006",
    name: "Heart Flowers Red Stone Kundan...",
    price: "₹1,392",
    original_price: "₹4,645",
    discount: "70% OFF",
    description: "Romantic heart-shaped earrings with red stone kundan work.",
    material: "Gold Plated",
    color: "Red",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.4,
    reviews: 112
  },
  {
    id: "007",
    name: "Priyaasi Geometric...",
    price: "₹2,537",
    original_price: "₹7,245",
    discount: "74% OFF",
    description: "Modern geometric design earrings with contemporary style.",
    material: "Gold Plated",
    color: "Gold",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.3,
    reviews: 98
  },
  {
    id: "008",
    name: "Emerald Delight - Green American...",
    price: "₹2,036",
    original_price: "₹6,945",
    discount: "71% OFF",
    description: "Stunning emerald green earrings with American diamond accents.",
    material: "Gold Plated",
    color: "Green",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.5,
    reviews: 134
  },
  {
    id: "009",
    name: "Blue Block Flower American...",
    price: "₹3,415",
    original_price: "₹12,245",
    discount: "72% OFF",
    description: "Beautiful blue floral earrings with American diamond work.",
    material: "Gold Plated",
    color: "Blue",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.6,
    reviews: 156
  },
  {
    id: "010",
    name: "Priyaasi Ruby Oval...",
    price: "₹1,896",
    original_price: "₹6,945",
    discount: "73% OFF",
    description: "Elegant ruby oval earrings with traditional design.",
    material: "Gold Plated",
    color: "Red",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.4,
    reviews: 108
  },
  {
    id: "011",
    name: "Stunning Green Floral Leaf AD...",
    price: "₹1,038",
    original_price: "₹4,245",
    discount: "76% OFF",
    description: "Stunning green floral leaf earrings with American diamond.",
    material: "Gold Plated",
    color: "Green",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.2,
    reviews: 89
  },
  {
    id: "012",
    name: "Royal Odyssey - Colourful Beads...",
    price: "₹3,192",
    original_price: "₹8,024",
    discount: "60% OFF",
    description: "Royal colorful beaded necklace with intricate design.",
    material: "Gold Plated",
    color: "Multi-Color",
    size: "Adjustable",
    category: "Necklaces",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.7,
    reviews: 178
  },
  {
    id: "013",
    name: "Pretty Polki Kundan Studded...",
    price: "₹642",
    original_price: "₹2,749",
    discount: "77% OFF",
    description: "Pretty polki kundan studded earrings with traditional work.",
    material: "Gold Plated",
    color: "Gold",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.1,
    reviews: 72
  },
  {
    id: "014",
    name: "Multi Color Kundan Paris...",
    price: "₹1,287",
    original_price: "₹4,999",
    discount: "74% OFF",
    description: "Multi-color kundan earrings with Parisian style.",
    material: "Gold Plated",
    color: "Multi-Color",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.3,
    reviews: 94
  },
  {
    id: "015",
    name: "Chand Noor - Floral American...",
    price: "₹812",
    original_price: "₹2,745",
    discount: "70% OFF",
    description: "Chand Noor floral earrings with American diamond work.",
    material: "Gold Plated",
    color: "Gold",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.0,
    reviews: 68
  },
  {
    id: "016",
    name: "Dreamy Drops - American...",
    price: "₹1,096",
    original_price: "₹3,999",
    discount: "73% OFF",
    description: "Dreamy drop earrings with American diamond accents.",
    material: "Gold Plated",
    color: "Gold",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.2,
    reviews: 85
  },
  {
    id: "017",
    name: "Eternity Band - Rhodium Plated...",
    price: "₹642",
    original_price: "₹1,499",
    discount: "56% OFF",
    description: "Elegant eternity band ring with rhodium plating.",
    material: "Rhodium Plated",
    color: "Silver",
    size: "Adjustable",
    category: "Rings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.1,
    reviews: 73
  },
  {
    id: "018",
    name: "Priyaasi Sea Green Studded...",
    price: "₹3,606",
    original_price: "₹13,945",
    discount: "74% OFF",
    description: "Beautiful sea green studded earrings with ocean-inspired design.",
    material: "Gold Plated",
    color: "Green",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.6,
    reviews: 142
  },
  {
    id: "019",
    name: "Blue Floral Block Drop American...",
    price: "₹3,179",
    original_price: "₹12,245",
    discount: "74% OFF",
    description: "Blue floral block drop earrings with American diamond work.",
    material: "Gold Plated",
    color: "Blue",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.5,
    reviews: 127
  },
  {
    id: "020",
    name: "Green Floral Drop AD Silver-Plated...",
    price: "₹2,345",
    original_price: "₹8,999",
    discount: "74% OFF",
    description: "Green floral drop earrings with silver plating and American diamond.",
    material: "Silver Plated",
    color: "Green",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.3,
    reviews: 96
  },
  {
    id: "021",
    name: "Star Struck - White American...",
    price: "₹569",
    original_price: "₹2,399",
    discount: "76% OFF",
    description: "Star struck earrings with white American diamond work.",
    material: "Gold Plated",
    color: "White",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.0,
    reviews: 71
  },
  {
    id: "022",
    name: "Dazzle Date - American...",
    price: "₹1,402",
    original_price: "₹5,627",
    discount: "75% OFF",
    description: "Dazzling earrings perfect for special dates and occasions.",
    material: "Gold Plated",
    color: "Gold",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.4,
    reviews: 103
  },
  {
    id: "023",
    name: "Pushp Bela - Kemp Stones...",
    price: "₹2,481",
    original_price: "₹6,945",
    discount: "65% OFF",
    description: "Pushp Bela earrings with kemp stones and floral design.",
    material: "Gold Plated",
    color: "Gold",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.2,
    reviews: 88
  },
  {
    id: "024",
    name: "Priyaasi Leaf Pearl AD Rose...",
    price: "₹1,553",
    original_price: "₹6,245",
    discount: "75% OFF",
    description: "Priyaasi leaf pearl earrings with rose gold accents.",
    material: "Rose Gold Plated",
    color: "Pink",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.5,
    reviews: 119
  },
  {
    id: "025",
    name: "Priyaasi Pink Kundan Multicol...",
    price: "₹2,541",
    original_price: "₹9,999",
    discount: "75% OFF",
    description: "Priyaasi pink kundan earrings with multicolor design.",
    material: "Gold Plated",
    color: "Pink",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.4,
    reviews: 107
  },
  {
    id: "026",
    name: "Black Kundan Enameled Stones...",
    price: "₹1,666",
    original_price: "₹8,245",
    discount: "80% OFF",
    description: "Black kundan enameled stone earrings with traditional work.",
    material: "Gold Plated",
    color: "Black",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.3,
    reviews: 92
  },
  {
    id: "027",
    name: "Royal Blue Sapphire Diamond Ring",
    title: "Royal Blue Sapphire Diamond Ring",
    price: "₹4,299",
    original_price: "₹12,999",
    discount: "67% OFF",
    description: "Exquisite royal blue sapphire ring with diamond accents. Perfect for special occasions and gifting.",
    material: "Sapphire & Diamond",
    color: "Royal Blue",
    size: "Adjustable",
    category: "Rings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.8,
    reviews: 156
  },
  {
    id: "028",
    name: "Pearl Drop Earrings Set",
    title: "Pearl Drop Earrings Set",
    price: "₹2,199",
    original_price: "₹6,999",
    discount: "69% OFF",
    description: "Elegant pearl drop earrings with intricate gold detailing. Timeless beauty for any occasion.",
    material: "Pearl & Gold Plated",
    color: "White Pearl",
    size: "One Size",
    category: "Earrings",
    images: ["/assets/slide1.webp", "/assets/cat1.webp", "/assets/bride.webp", "/assets/cocktail.webp"],
    inStock: true,
    rating: 4.6,
    reviews: 89
  },
];

export const bestSellersList = [
  {
    id: "001",
    name: "Priyaasi Traditional...",
    price: "₹1,774",
    original_price: "₹6,999",
    discount: "74% OFF",
  },
  {
    id: "002",
    name: "Priyaasi Magenta Leaf AD...",
    price: "₹1,506",
    original_price: "₹5,999",
    discount: "75% OFF",
  },
  {
    id: "003",
    name: "Priyaasi Solitaire American...",
    price: "₹696",
    original_price: "₹2,849",
    discount: "76% OFF",
  },
  {
    id: "004",
    name: "Fancy Folk - Kundan Studded...",
    price: "from ₹726",
    original_price: "₹1,500",
    discount: "52% OFF",
  },
];

export const trendingList = [
  {
    id: "001",
    name: "Priyaasi Traditional...",
    price: "₹1,774",
    original_price: "₹6,999",
    discount: "74% OFF",
  },
  {
    id: "002",
    name: "Priyaasi Magenta Leaf AD...",
    price: "₹1,506",
    original_price: "₹5,999",
    discount: "75% OFF",
  },
  {
    id: "003",
    name: "Priyaasi Solitaire American...",
    price: "₹696",
    original_price: "₹2,849",
    discount: "76% OFF",
  },
  {
    id: "004",
    name: "Fancy Folk - Kundan Studded...",
    price: "from ₹726",
    original_price: "₹1,500",
    discount: "52% OFF",
  },
];