export const productList = [
  {
    id: "001",
    name: "Priyaasi Traditional...",
    price: "₹1,774",
    original_price: "₹6,999",
    discount: "74% OFF",
  },
  {
    id: "002",
    name: "Priyaasi Magenta Leaf AD...",
    price: "₹1,506",
    original_price: "₹5,999",
    discount: "75% OFF",
  },
  {
    id: "003",
    name: "Priyaasi Solitaire American...",
    price: "₹696",
    original_price: "₹2,849",
    discount: "76% OFF",
  },
  {
    id: "004",
    name: "Fancy Folk - Kundan Studded...",
    price: "from ₹726",
    original_price: "₹1,500",
    discount: "52% OFF",
  },
  {
    id: "005",
    name: "Classic Curves - Gold Plated Half...",
    price: "₹537",
    original_price: "₹2,099",
    discount: "74% OFF",
  },
  {
    id: "006",
    name: "Heart Flowers Red Stone Kundan...",
    price: "₹1,392",
    original_price: "₹4,645",
    discount: "70% OFF",
  },
  {
    id: "007",
    name: "Priyaasi Geometric...",
    price: "₹2,537",
    original_price: "₹7,245",
    discount: "74% OFF",
  },
  {
    id: "008",
    name: "Emerald Delight - Green American...",
    price: "₹2,036",
    original_price: "₹6,945",
    discount: "71% OFF",
  },
  {
    id: "009",
    name: "Blue Block Flower American...",
    price: "₹3,415",
    original_price: "₹12,245",
    discount: "72% OFF",
  },
  {
    id: "010",
    name: "Priyaasi Ruby Oval...",
    price: "₹1,896",
    original_price: "₹6,945",
    discount: "73% OFF",
  },
  {
    id: "011",
    name: "Stunning Green Floral Leaf AD...",
    price: "₹1,038",
    original_price: "₹4,245",
    discount: "76% OFF",
  },
  {
    id: "012",
    name: "Royal Odyssey - Colourful Beads...",
    price: "₹3,192",
    original_price: "₹8,024",
    discount: "60% OFF",
  },
  {
    id: "013",
    name: "Pretty Polki Kundan Studded...",
    price: "₹642",
    original_price: "₹2,749",
    discount: "77% OFF",
  },
  {
    id: "014",
    name: "Multi Color Kundan Paris...",
    price: "from ₹1,287",
    original_price: "₹4,999",
    discount: "74% OFF",
  },
  {
    id: "015",
    name: "Chand Noor - Floral American...",
    price: "₹812",
    original_price: "₹2,745",
    discount: "70% OFF",
  },
  {
    id: "016",
    name: "Dreamy Drops - American...",
    price: "₹1,096",
    original_price: "₹3,999",
    discount: "73% OFF",
  },
  {
    id: "017",
    name: "Eternity Band - Rhodium Plated...",
    price: "₹642",
    original_price: "₹1,499",
    discount: "56% OFF",
  },
  {
    id: "018",
    name: "Priyaasi Sea Green Studded...",
    price: "₹3,606",
    original_price: "₹13,945",
    discount: "74% OFF",
  },
  {
    id: "019",
    name: "Blue Floral Block Drop American...",
    price: "₹3,179",
    original_price: "₹12,245",
    discount: "74% OFF",
  },
  {
    id: "020",
    name: "Green Floral Drop AD Silver-Plated...",
    price: "₹2,345",
    original_price: "₹8,999",
    discount: "74% OFF",
  },
  {
    id: "021",
    name: "Star Struck - White American...",
    price: "₹569",
    original_price: "₹2,399",
    discount: "76% OFF",
  },
  {
    id: "022",
    name: "Dazzle Date - American...",
    price: "from ₹1,402",
    original_price: "₹5,627",
    discount: "75% OFF",
  },
  {
    id: "023",
    name: "Pushp Bela - Kemp Stones...",
    price: "₹2,481",
    original_price: "₹6,945",
    discount: "65% OFF",
  },
  {
    id: "024",
    name: "Priyaasi Leaf Pearl AD Rose...",
    price: "₹1,553",
    original_price: "₹6,245",
    discount: "75% OFF",
  },
  {
    id: "025",
    name: "Priyaasi Pink Kundan Multicol...",
    price: "₹2,541",
    original_price: "₹9,999",
    discount: "75% OFF",
  },
  {
    id: "026",
    name: "Black Kundan Enameled Stones...",
    price: "₹1,666",
    original_price: "₹8,245",
    discount: "80% OFF",
  },
];

export const bestSellersList = [
  {
    id: "001",
    name: "Priyaasi Traditional...",
    price: "₹1,774",
    original_price: "₹6,999",
    discount: "74% OFF",
  },
  {
    id: "002",
    name: "Priyaasi Magenta Leaf AD...",
    price: "₹1,506",
    original_price: "₹5,999",
    discount: "75% OFF",
  },
  {
    id: "003",
    name: "Priyaasi Solitaire American...",
    price: "₹696",
    original_price: "₹2,849",
    discount: "76% OFF",
  },
  {
    id: "004",
    name: "Fancy Folk - Kundan Studded...",
    price: "from ₹726",
    original_price: "₹1,500",
    discount: "52% OFF",
  },
];

export const trendingList = [
  {
    id: "001",
    name: "Priyaasi Traditional...",
    price: "₹1,774",
    original_price: "₹6,999",
    discount: "74% OFF",
  },
  {
    id: "002",
    name: "Priyaasi Magenta Leaf AD...",
    price: "₹1,506",
    original_price: "₹5,999",
    discount: "75% OFF",
  },
  {
    id: "003",
    name: "Priyaasi Solitaire American...",
    price: "₹696",
    original_price: "₹2,849",
    discount: "76% OFF",
  },
  {
    id: "004",
    name: "Fancy Folk - Kundan Studded...",
    price: "from ₹726",
    original_price: "₹1,500",
    discount: "52% OFF",
  },
];